### ISSUE TITLE
Print can't convert boolean to string.

### ISSUE THREAD

**Issue by heromk** [TinyPandas/TinyGuardianRS#5]
When you try to print a boolean using the bot it gives this error `callback error: error converting Lua boolean to String (expected string or number):`

How to replicate:

`tg!lua print(true);`

Edit: I just tested it and it doesnt work with any of these either: `nil, tables, function`

**Comment by TinyPandas** [comment]
Fixed in commit: https://github.com/TinyPandas/TinyGuardianRS/commit/7d3fe636d87005b097535c292c6876921613dbaa

**Comment by TinyPandas** [comment]
Fix further breaks output, displaying all `print` calls in `T(U)` manner. Where `T` is type of output, and `U` is value of output. With strings this displays `String(String(Ref(2)))` instead of the actual string.

**Comment by TinyPandas** [comment]
Fixed https://github.com/TinyPandas/TinyGuardianRS/commit/48cfaf4e444895c95fbdfe1f18ac8eef0bb0b11d
